  global_frame: /odom
  robot_base_frame: /base_link
  plugins:
    - {name: obstacles, type: "costmap_2d::ObstacleLayer"}
    - {name: inflated, type: "costmap_2d::InflationLayer"}

  update_frequency: 15.0
  publish_frequency: 15.0
  static_map: false
  rolling_window: true
  width: 10.0
  height: 10.0
  resolution: 0.05
  origin_x: -5.0
  origin_y: -5.0
  origin_z: 0.0

  transform_tolerance: 0.3
  footprint: [[-0.20, 0.10], [-0.20, -0.20], [0.20, -0.20], [0.20, 0.10]]
  footprint_padding: 0.03

  obstacles:
    observation_sources: scan
    scan: {topic: /scan, data_type: LaserScan, expected_update_rate: 0.50, obstacle_range: 3.0, raytrace_range: 5.0, observation_persistence: 0, marking: true, clearing: true, min_obstacle_height: 0.05, max_obstacle_height: 1.0, inf_is_valid: true}
    track_unknown_space: true
    global_frame: /odom
    robot_base_frame: /base_link

  inflated:
    inflation_radius: 0.2
    cost_scaling_factor: 1.0


