  global_frame: /map
  robot_base_frame: /base_link
  update_frequency: 6.0
  static_map: false

  transform_tolerance: 0.5
  footprint: [[-0.30, 0.30], [-0.30, -0.30], [0.17, -0.30], [0.17, 0.30]]
  footprint_padding: 0.03

  plugins:  
    - {name: staticmap, type: "costmap_2d::StaticLayer"}
    - {name: obstacles, type: "costmap_2d::ObstacleLayer"}
    - {name: inflated, type: "costmap_2d::InflationLayer"}

  obstacles:
    observation_sources: scan
    scan: {topic: /scan, data_type: LaserScan, expected_update_rate: 0.50, obstacle_range: 3.0, raytrace_range: 5.0, observation_persistence: 0, marking: true, clearing: true, min_obstacle_height: 0.10, max_obstacle_height: 5.0, inf_is_valid: true}
    track_unknown_space: no
    global_frame: /map
    robot_base_frame: /base_link

  inflated:
    inflation_radius: 0.40
    cost_scaling_factor: 0.8
